### ISSUE TITLE
Thumbnails fail to generate/Covers are not shown

### ISSUE THREAD

**Issue by CHRONiCiTY** [linuxserver/docker-airsonic-advanced#6]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Create thumbnails for your media and show your covers

## Current Behavior
Thumbnails are not generated, covers are not shown and the log is riddled with errors

## Steps to Reproduce
Just create the container

## Environment
**OS:** Debian GNU/Linux 10 (buster)
**CPU architecture:** x86_64
**How docker service was installed:** From the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
docker run -d \
	-e JAVA_OPTS="-Dserver.forward-headers-strategy=native -Xmx1024m" -e TZ=Europe/Stockholm \
	--hostname=$NAME \
	--ip=$IP \
	--mac-address=$MAC \
	--name=$NAME --network=macvlan \
	--restart=always \
	-v /mnt/SSD/docker/$NAME/config:/config \
	-v /mnt/SSD/docker/$NAME/music:/music -v /mnt/SSD/docker/$NAME/podcasts:/podcasts -v /mnt/SSD/docker/$NAME/playlists:/playlists \
	-v /mnt/HDD/Storage:/mnt/HDD/Storage:ro \
	$REPO

## Docker logs
[log.log](https://github.com/linuxserver/docker-airsonic-advanced/files/7856149/log.log)

**Comment by TheSpad** [comment]
I think it's an issue with the headless JRE, I'll spin up a test image for you to try

**Comment by TheSpad** [comment]
@CHRONiCiTY please try `docker.io/lspipepr/airsonic-advanced:11.0.0-SNAPSHOT.20220110133315-pkg-cf4e5d20-pr-7` and see if it fixes your issue.

**Comment by CHRONiCiTY** [comment]
Yep, that did the trick! :)
